### ISSUE TITLE
EscapeGcop on AdoDotNetDataProviderFactory

### ISSUE THREAD

**Issue by Karvan** [Geeksltd/GCop#101]
@PaymonK , Could you please add` [EscapeGCop("Auto generated code.")] `
to `@AdoDotNetDataProviderFactory `class.

**Comment by PaymonK** [comment]
Already done

With kind regards,
Paymon Khamooshi
Director
Geeks Ltd
www.geeks.ltd
0845 643 6229

> On 19 Apr 2018, at 11:50, Karvan <notifications@github.com> wrote:
> 
> @PaymonK , Could you please add [EscapeGCop("Auto generated code.")]
> to @adodotnetdataproviderfactory class.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 


*Geeks Ltd*

_Bespoke Web and Software Solutions
_www.geeks.ltd.uk 
<http://www.geeks.ltd.uk/>





​


​
CONFIDENTIALITY & DISCLAIMER: This 
message and any attachments are confidential, proprietary, and may be 
privileged.  If this message was misdirected, Geeks Ltd does not waive any 
confidentiality or privilege.  If you are not the intended recipient, 
please notify us immediately and destroy the message without disclosing its 
contents to anyone.  Any distribution, use or copying of this e-mail or the 
information it contains by other than an intended recipient is 
unauthorized. Any offer or acceptance contained within or implied by this 
Email message is made Subject to Contract, Additionally, where this Email 
message is sent in connection with a contentious issue, the contents are 
Without Prejudice.
