### ISSUE TITLE
GCop624 to be split

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#108]
See https://github.com/Geeksltd/GCop/blob/master/Rules/GCop624.md

Those should be 2 different rules.

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackage\ef2a9ed79a463c81e61ef880065dcab18abfb151](https://gitlab.com/Paymon/GCop/tree/ef2a9ed79a463c81e61ef880065dcab18abfb151)

**Comment by Foroughi** [comment]
### Technical Information

- **GCop624** kicks in now only if we have `myCollection.Any(c => c != categoryId)` 
- **GCop640** (New rule) kicks in only if we have `myCollection.Any(c => c == categoryId)`
