### ISSUE TITLE
Remove GCop403

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#109]
It seems like Visual Studio now has this rule built-in, so there is no need for it anymore:
https://github.com/Geeksltd/GCop/blob/master/Rules/GCop403.md

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackages\d183f9682cfb5c88c356736d9cd26d4b62f52d1d](https://gitlab.com/Paymon/GCop/tree/d183f9682cfb5c88c356736d9cd26d4b62f52d1d)
