### ISSUE TITLE
New rule for [Authorize] attribute

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#125]
For a class, if:
- Class's name ends with Api or ApiController,
- It declares the [Authorize] attribute
- It references Olive namespace

Then warn to say: "If this is an Api controller, instead of [Authorize] use [AuthorizeApi] attribute."

**Comment by Foroughi** [comment]
@reporter : Added by Karvan on [NuGetPackages\8d4949b4174b1519ee6c7572e0a067de2bc87ae9](https://gitlab.com/Paymon/GCop/tree/8d4949b4174b1519ee6c7572e0a067de2bc87ae9)

Fixed some tiny issues and added its unit test on [NuGetPackages\6315e7775dc6c91cc9e9d048adb50314209ae005](https://gitlab.com/Paymon/GCop/tree/6315e7775dc6c91cc9e9d048adb50314209ae005)
