### ISSUE TITLE
GCop installation problem

### ISSUE THREAD

**Issue by marjanjavid** [Geeksltd/GCop#131]
After creating a M# ASP.NET Core-MVC application and installing GCop, I have lots of  NU1701 warnings in my error list which are visible in this picture. As I talked with Karvan this problem should be checked.

![1](https://user-images.githubusercontent.com/20684649/39470565-ae2955e8-4d53-11e8-8519-7f9b8d9ff049.PNG)

**Comment by Karvan** [comment]
.net core 2

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackages\d8658c1ffeaf0bc5a7d543e78083d29283be0348](https://gitlab.com/Paymon/GCop/tree/d8658c1ffeaf0bc5a7d543e78083d29283be0348)
