### ISSUE TITLE
GCop524: Two rules in one?

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#132]
See the documentatoin:
https://github.com/Geeksltd/GCop/blob/master/Rules/GCop524.md

The `remove private` message should be a different rule from `Turn a private property into a field`.

**Comment by Foroughi** [comment]
@PaymonK  According to the codes, GCop524 is just about removing the private. I can not anything about turning a private property into a field there.

**Comment by PaymonK** [comment]
It was maybe a documentation error
