### ISSUE TITLE
Delete GCop127

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#133]
This rule is unnecessry https://github.com/Geeksltd/GCop/blob/master/Rules/GCop127.md

**Comment by Foroughi** [comment]
@reporter Fixed on [NuGetPackages\c45002e955a794a5f567be46280f87e4c9883740](https://gitlab.com/Paymon/GCop/tree/c45002e955a794a5f567be46280f87e4c9883740)
