### ISSUE TITLE
Prevent calling Task.Result property

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#15]
This is an M#/Olive specific rule.

Error message:
**_The Result property of the Task object should never be called.  Either properly await it, or call GetAlreadyCompletedResult()._**

**Comment by PaymonK** [comment]
1. Yes.

2.  Zebble too. It's being added now to Zebble.

**Comment by Foroughi** [comment]
@reporter: I'm doing the task in the way you asked, but I think it could be a general C# project as well (not only a M#/Olive/Zebble rule). 
Obviously, the rule is looking for Task.Result statement which is a valid C# syntax. But if your worry about `GetAlreadyCompletedResult()` method, I should raise this point that in this rule, that method is playing a `Code Fixer` role. here is the whole scenario I'm pointing out : 

The rule (while is not a M#/Zebble/Olive rule) is looking for Task.Result. In case it found any, it will report a warning. so developers will get informed about this rule. now it's the time to suggest them for the possible code fixer. here are the possible options as you mentioned : 

- Use `await` instead
- Use `GetAlreadyCompletedResult()`

Note: The second option will be suggested to use if only the project is a M#/Zebble/Olive project.

So I think the rule can be applied to in normal C# projects. the only difference is about showing or not showing the second option as code fixer. 

Let me know if you want me to change it.

**Comment by PaymonK** [comment]
@Foroughi  We can't show a warning to say you MUST use `await` because it many scenarios it's not applicable. I think it's fine to keep it a GeeksExtensions only rule.

**Comment by Foroughi** [comment]
Here are some details of the new rule : 

## General Details:

- ID : **543**
- Category : **Usage**
- Message : **Non-public methods should not need basic argument validation**
- Severity : **Usage**
- Package : **GCop.Usage**

## Technical Details : 

Every Usage of `System.Threading.Tasks.Result` will cause the rule to kick in.

## Test Result :

- [X] func1().Result
- [X] var t = func1(); return t.Result


In case of any changes needs to be done on this rule please let me know.
