### ISSUE TITLE
GCop618 vs GCop 516

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#151]
What is the difference between these two rules? Should they be merged? Or are they two different things?

https://github.com/Geeksltd/GCop/blob/master/Rules/GCop618.md

**Comment by Foroughi** [comment]
@PaymonK here is the difference : 

GCop516 is assuming **there is no** static method named FindBy{PropertyName} so it suggests dev to mark {PropertyName} as unique and then use the generated method.

GCop618 is assuming **there is** a static method named FindBy{PropertyName} so it suggests dev to use it. 


@PaymonK It's up to you now if you want to merge them or not. But if you ask me, I'm gonna say: merge them together

**Comment by Foroughi** [comment]
@marjanjavid according to this, the example I gave you for GCop618 is wrong. Here is the correct one : 

namespace MSharp.Framework
{
    class Database
    {
         public method1()
         {
                Find(rec => rec.PropertyX)
         }
    }
}

**Comment by Karvan** [comment]
@Foroughi Please merge them they have a very same purpose.

**Comment by marjanjavid** [comment]
@Foroughi So please announce me after you merged them, because i should change the documents.
thank u

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackage\797d3d161498daa5602d5f66ee6c9e510a429916](https://gitlab.com/Paymon/GCop/tree/166bd0992c2bd8e087e1aa0643f7a0c63033acad)

@marjanjavid  You may wanna change the docs now

**Comment by marjanjavid** [comment]
I checked this rule. It works fine
