### ISSUE TITLE
GCop.Core error loop

### ISSUE THREAD

**Issue by anaSelegova2018** [Geeksltd/GCop#180]
Hi, I have installed GCop.Extra and GCop.Collections with GCopCommon. After rebuilding a project, I have received an endless loop of errors. I have uninstalled them. However I am getting same errors. My visual studio is unusable now.
![gcop error](https://user-images.githubusercontent.com/40832220/42281707-4c93f100-7f9c-11e8-8daf-f43daeec91e4.JPG)
Please see image attached.

**Comment by Foroughi** [comment]
@anaSelegova2018 Would you please let me know what is the project type you're getting this endless loop alerts on?

**Comment by Karvan** [comment]
@Foroughi Apparently we have this issue sometimes. not happening always for the same project and on the same machine. 

@anaSelegova2018 it shouldn't be just the GCop.Extra. we will look into the windows event to see what can we find there.

**Comment by Karvan** [comment]
Fixed. it's related to old GCop.Extra.
