### ISSUE TITLE
Some Gcop warnings don't show the ID

### ISSUE THREAD

**Issue by Karvan** [Geeksltd/GCop#181]
GCop 406
![gcop406](https://user-images.githubusercontent.com/20923968/42634852-519c9792-85dc-11e8-8e01-189d80ac3462.png)

GCop 548
![gcop 546](https://user-images.githubusercontent.com/20923968/42634900-7f17a7b6-85dc-11e8-9e78-850cd9d69983.png)

**Comment by Foroughi** [comment]
@karvan I just checked both rules and both seems correct to me, seems its an unexpected behavior of Roslyn.
