### ISSUE TITLE
GCop 124 should be removed

### ISSUE THREAD

**Issue by HamidTheGeek** [Geeksltd/GCop#184]
As we can define and assign the converted value of the TryParse methods at the same line. We do not need this rule anymore.

Currently, it forces us to change this method
``` C#
bool IsNumberAndBetween(string value, int min, int max) =>
    int.TryParse(value, out int intValue) && intValue.LimitWithin(min, max) == intValue;
```
in to 

``` C#
bool IsNumberAndBetween2(string value, int min, int max)
{
    var intValue = value.TryParseAs<int>();
    return intValue.HasValue && intValue.Value.LimitWithin(min, max) == intValue;
}
```

**Comment by Foroughi** [comment]
@Karvan @PaymonK We have two solutions to avoid this :

1- Check if the out decorated parameter is being used in the current line or not (which is a little bit tricky. I'm not sure about the details but generally I mean we can add an exception to the rule logic to avoid this, like if the TryParse is being used in a binary statement)
2- Remove the rule

Please let me know which one do you guys prefer

**Comment by HamidTheGeek** [comment]
Hi Ali,

Paymon agrees to remove that.

**Comment by Foroughi** [comment]
@HamidTheGeek Hi Hamid. 
The rule has been removed on [Development\a59cea1ddfee46df909b97dc90bf5dc004e6fe4e](https://gitlab.com/Paymon/GCop/tree/a59cea1ddfee46df909b97dc90bf5dc004e6fe4e)
