### ISSUE TITLE
Redundant   new string[] { }

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#197]
If you see
`InstanceAccessors(new string[] { "High", "Medium", "Low" });`
or
`InstanceAccessors(new [] { "High", "Medium", "Low" });`

it should be changed to 
`InstanceAccessors("High", "Medium", "Low");`

**Comment by Foroughi** [comment]
@reporter : Fixed on [Development/7b915a43a955a22609912c43acbc250ebe5604a6](https://gitlab.com/Paymon/GCop/tree/7b915a43a955a22609912c43acbc250ebe5604a6)
