### ISSUE TITLE
Prevent multiple class scope declaration

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#21]
When you have a number of partial files for a class, C# compiler allows you to duplicate class modifiers such as static, public, internal, ... on all of them as long as they are the same. To prevent confusion and make it more explicit, GCop should warn to say **"Only one partial file for a class should specify the class modifiers (public, static, ...)"**

**Comment by Karvan** [comment]
This rule should add to the GCopExtra extension.

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackages\6ae1ecb0982a194ac65174192df18a3c0012fd74](https://gitlab.com/Paymon/GCop/commit/6ae1ecb0982a194ac65174192df18a3c0012fd74)

**Comment by Foroughi** [comment]
@reporter : The new rule has been added. Here is the details :

## Specifications : 

- **Code** : GCop439
- **Package** : GCop.Extra
- **Secuirty Level** : Warning
- **Warning Message** : Only one partial file for a class should specify the class modifiers (public, static, ...)

## Technical Informations
In case of more than one instances of a partial class decorated with one of the following modifiers, the rule will kick in : 

- Public
- Private
- Static
- Internal


In case of any other change needs to be applied to this rule, please let me know
