### ISSUE TITLE
Empty If block and commented Else block

### ISSUE THREAD

**Issue by marjanjavid** [Geeksltd/GCop#226]
@Karvan I think in the case below we should fire a warning. this could seems redundant
if (true)
{
}
else
{
     //int x = 3;
}

**Comment by Foroughi** [comment]
@marjanjavid Does GCop show any warning on this code ?!

**Comment by marjanjavid** [comment]
@Foroughi Let me explain, At this time, which I am testing a not updated GCop.UAT, GCop693 is firing this.
But pay attention that Payman asked us to remove this warning for commented else blocks. So if we test the latest GCop.UAT package, we wouldn't have any warning in this case(sample above)
