### ISSUE TITLE
"c#:" prefix

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#229]
If you see "c#:" at the beginning of any string value, warn to say:
"Use cs(...)" method instead of the "c#:" prefix".

It needs an auto fixer as well.

**Comment by marjanjavid** [comment]
Please give me the Id of this rule. Thank you

**Comment by marjanjavid** [comment]
It is GCop557

**Comment by marjanjavid** [comment]
It is tested on GCop2.6.0 and works fine. The markdown file is added . There is  a problem about the auto fix which will follow throw issue #302
