### ISSUE TITLE
.SendItemId() use

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#235]
If you see `.Send("item", "item.ID")` such as in the following example:

```c#
Button("Edit").OnClick(x => x.Go<SomePage>().Send("item", "item.ID"));
```

Then warn to say: `Use the shortcut .SendItemId()` instead.

**Comment by marjanjavid** [comment]
@Foroughi please send me the Id of this rule

**Comment by marjanjavid** [comment]
I found it. It is GCop556

**Comment by marjanjavid** [comment]
It is checked on GCop2.6.0 and works fine. But its message needs edit which is explained on issue #301

**Comment by marjanjavid** [comment]
It works fine so I will close this
