### ISSUE TITLE
Some GCop warnings are mistake 

### ISSUE THREAD

**Issue by Hatef-Rostamkhani** [Geeksltd/GCop#238]
Some GCop warnings are mistake
.HasMany on System.Windows.Controls.ItemCollection also  .Any on System.Data.DataRowCollection
![image](https://user-images.githubusercontent.com/10432308/49017587-74b5d300-f19e-11e8-9162-50696330af4d.png)

**Comment by Foroughi** [comment]
@Hatef-Rostamkhani Hi, thank you for letting me know about this, but I'm gonna need a little bit more details on this issue. Would you please to describe it more ?! What do you mean by ".HasMany on System.Windows.Controls.ItemCollection" ?!

**Comment by Hatef-Rostamkhani** [comment]
Hi @Foroughi , Yes. exactly
I used DataRowCollection and GCop warning me, use Any() but has no extension for the Any() method also System.Windows.Controls.ItemCollection Gcop has warning to use HasMany() but has no extension for HasMany() method.

**Comment by Foroughi** [comment]
It's fixed now. Any collection which is not inherited from generic `IEnumerable `would have no effect on the rule (in this case `ObjectCollection`)

@Hatef-Rostamkhani You may wanna wait for the next release.

**Comment by marjanjavid** [comment]
As I checked GCop2.6.0 this issue is solved. @Hatef-Rostamkhani would you please check it and close this issue if it is solved?
