### ISSUE TITLE
Fix the GCop rules of the GCop source itself. 

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#24]
The GCop source should be itself clean. Also apply Tidy C# (VS extension) on it.

**Comment by Foroughi** [comment]
@Reporter,  Fixed on [NuGetPackage\27f026554f719e729bd198b8c33bcfe4bfb27e0d](https://gitlab.com/Paymon/GCop/commit/27f026554f719e729bd198b8c33bcfe4bfb27e0d)
