### ISSUE TITLE
Nuspec icon

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#26]
In the GCop nuspec files add IconUrl to be 

https://raw.githubusercontent.com/Geeksltd/GCop/master/GCopLogo.png

**Comment by Foroughi** [comment]
Fixed on [NuGetPackages/2644df057ad6dcc8fb78558c954746d242779ab0](https://gitlab.com/Paymon/GCop/commit/2644df057ad6dcc8fb78558c954746d242779ab0)
