### ISSUE TITLE
GCop 406 causes GCop 139 and back

### ISSUE THREAD

**Issue by tobiasoort** [Geeksltd/GCop#264]
`private const int myConstNumber = 7;`
gets error: _Warning GCop406: Mark myConstNumber field as read-only. (GCop406)_
If I change it to:

`private static readonly int myConstNumber = 7;`
the error becomes: _Warning GCop139: Use constant instead of field. (GCop139)_

**Comment by Karvan** [comment]
@Foroughi I've seen this issue before. Could you please priorities this one?

**Comment by Foroughi** [comment]
@Karvan  Sure ,ill keep you updated ASAP

**Comment by Foroughi** [comment]
Dup #252 . GCop406  wont kick in for the `const `properties in the next release.
