### ISSUE TITLE
GCop648 clarification

### ISSUE THREAD

**Issue by sungam3r** [Geeksltd/GCop#287]
The rule says:

> The Remove() extension method on string is more readable...

Is this an existing method or is it recommended to write it yourself? I have not found such an extension method in .NET.

**Comment by Foroughi** [comment]
@sungam3r That's a method of `String` class in `System.Runtime` namespace in `Net Standard 1.3`

**Comment by sungam3r** [comment]
I don`t understand. All netstandard and core versions contain only int overloads: https://docs.microsoft.com/en-us/dotnet/api/system.string.remove?view=netstandard-1.3

Example:

```c#
 string hhh = "ddd";
 hhh.Replace("a", ""); // GCop648	Use hhh.Remove("a") instead	
```
After fix:
```c#
string hhh = "ddd";
hhh.Replace("a"); // CS1501	No overload for method 'Replace' takes 1 arguments	
```

**Comment by Foroughi** [comment]
@sungam3r quick question, why do you have still `Replace` method after the fix ? is that a typo or the rule is not fixing the code properly ?!

**Comment by sungam3r** [comment]
Sorry. It is a typo.

Example:

```cs
 string hhh = "ddd";
 hhh.Replace("a", ""); // GCop648	Use hhh.Remove("a") instead	
```

After fix:

```cs
string hhh = "ddd";
hhh.Remove("a"); // CS1503 Argument 1: cannot convert from 'string' to 'int'	
```

**Comment by Foroughi** [comment]
@sungam3r Your right, I Doesn't make sense.

@marjanjavid @Karvan  has Geeks implemented any other overload for `Remove` method in any of those 3 third-party libraries?

**Comment by Karvan** [comment]
@Foroughi It's an MSharp extension. Please move it to `Olive/MSharp/Zebble` Package.

**Comment by marjanjavid** [comment]
This is moved to `Olive/MSharp/Zebble` package on this commit;
https://gitlab.com/Paymon/GCop/commit/251ea928edb83c2cfa725e3d8848ead3affff08d

**Comment by marjanjavid** [comment]
This is fixed on GCop2.6.1
