### ISSUE TITLE
Remove rule GCop212

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#31]
Later on we need to come up with a more thorough rule to analyse naming using dictionary, etc.

**Comment by Foroughi** [comment]
Fixed on `SlnMerge/64c3ebf4807bb5be5bba77287258ea584bd5cb1a`

**Comment by Foroughi** [comment]
FYI from now on, if you set `IsEnabledByDefault = false` of a rule description. that rule won't raise any alarm. more like that rule a completely disabled or even omitted.
