### ISSUE TITLE
GCop 615 should apply for M#, Olive and Zebble references only

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#32]
https://github.com/Geeksltd/GCop/blob/master/Rules/GCop615.md

**Comment by marjanjavid** [comment]
GCop615 should only come into effect for proejcts that reference M# Framework.Because on c# projects we dont have .None in linq

**Comment by marjanjavid** [comment]
on GCop204 and in sample below we should see an error but it doesnt create any error for that.
private string _n;
    public string Name
    {
        get { return this._n; }
        set { this._n = value; }
    }

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackages\b3deb0f3e619a4f29488fc19aacfdbb172d3d8c3](https://gitlab.com/Paymon/GCop/commit/b3deb0f3e619a4f29488fc19aacfdbb172d3d8c3)
