### ISSUE TITLE
Warning about  GCop in a .NET Fx 4.6 project

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#4]
IDE1003	Analyzer assembly 
'C:\...\analyzers\dotnet\cs\GCop.Thread.dll' depends on 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' but it was not found. 

Analyzers may not run correctly unless the missing assembly is added as an analyzer reference as well.

**Comment by mohsad06** [comment]
@PaymonK That's a random behavior on behalf of the latest .NET analyzer platform. The warning you mentioned is not stopping GCop from working and will disappear after doing random actions. For example, if you change the .NET target framework version to 4.6.1 and then change back to 4.6 it will disappear.
I know it's not a fix, it's just a workaround, for now. Moreover, if you see GCop warnings in your project, you should be fine.

**Comment by Karvan** [comment]
For now, we have a workaround to fix this. 
Adding NetStandard NuGet to the project and setting the netstandard library as the analyser for the website. But we keep it in progress (milestone 2) as we need a more handy solution.
