### ISSUE TITLE
Remove GCop rules from .designer.cs files

### ISSUE THREAD

**Issue by marjanjavid** [Geeksltd/GCop#46]
GCop rules should all be skipped if a file name ends with .designer.cs.

**Comment by Foroughi** [comment]
@reporter : Already fixed on [NuGetPackages\f4a7002c062df7388feef67ecdb68a4683a3dfec](https://gitlab.com/Paymon/GCop/commit/f4a7002c062df7388feef67ecdb68a4683a3dfec) at March 21th
