### ISSUE TITLE
Disable Rule 131

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#54]
This rule is unnecessary.  The extension method alternative is not much better anyway.
https://github.com/Geeksltd/GCop/blob/master/Rules/GCop131.md

**Comment by Foroughi** [comment]
Fixed on [NuGetPackages/ce7672e6a85ebc482c4b7daaddf3d01a608cabfe](https://gitlab.com/Paymon/GCop/commit/ce7672e6a85ebc482c4b7daaddf3d01a608cabfe)
