### ISSUE TITLE
Change the text for 179

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#57]
Change the error text to:

"Do not hardcode numbers, strings or other values. Use constant fields, enums, config files or database as appropriate."

**Comment by Foroughi** [comment]
@Reporter , Fixed on [NuGetPackages\55fa8c94d8fb41cbdfd93a20018155d95a7df5fa](https://gitlab.com/Paymon/GCop/commit/55fa8c94d8fb41cbdfd93a20018155d95a7df5fa)
