### ISSUE TITLE
Two rules exist for GCop605

### ISSUE THREAD

**Issue by Karvan** [Geeksltd/GCop#66]

**Comment by Foroughi** [comment]
@reporter : There were 2 issues with id 605

605 - AvoidUsingChangeTypeMethodAnalyzer  (GCop.GeeksExtensionMethods)
605 - GCop.GeeksExtensionMethods (GCop.Common)

I changed the second one to 608

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackages\481771a549f208989145b755709ba9e7a4d26326](https://gitlab.com/Paymon/GCop/commit/481771a549f208989145b755709ba9e7a4d26326)
