### ISSUE TITLE
@GCop 311

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#77]
Skip this warning if the code is throwing ex.InnerException

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackages\603b41929187a4f920bc0f426111895212f16f24](https://gitlab.com/Paymon/GCop/commit/603b41929187a4f920bc0f426111895212f16f24)

## Test Results :

- [ ] try {} catch { throw; }      
- [X] try {} catch(Exception ex) { throw ex; }  
- [ ] try {} catch(Exception ex) { throw ex.InnerException; }
