### ISSUE TITLE
NuGet Meta Deployment

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#83]
Currently the GCop.GeeksExtension holds the rules related to Olive/Zebble and MSharp projects.
So such projects currently have to reference both **GCop.Basics** and **GCop.GeeksExtension** packages.

## Instead we should: 

1. Rename GCop.GeeksExtension to specifically GCop.OliveZebbleMSharp.
2. Rename GCop.Basics to GCop.All.Common
2. Add another meta package called "GCop.All.Geeks" which adds dependencies to both GCop.All.Common and GCop.OliveZebbleMSharp.

This way we can only reference the GCop.All.Geeks package in our projects instead of two.

## Description
In the GCop.All.Common nuspec file set description to "A meta-package that includes all basic GCop components that apply to all .NET projects. Use this if your project is not Zebble, Olive or M# based."

And for GCop.All.Geeks set description to "For M#, Zebble and Olive projects, reference only this meta package, which gives you everything."

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackages\e8b3f0042d8a7ac28bb313e54bf3c633963ad1a9](https://gitlab.com/Paymon/GCop/commit/e8b3f0042d8a7ac28bb313e54bf3c633963ad1a9)
