### ISSUE TITLE
Rule 430 (M# Compatibility)

### ISSUE THREAD

**Issue by Karvan** [Geeksltd/GCop#9]
Nullable GUID and DateTime don't have the `HasValue()` extension.

We have to ignore this rule for them or Paymon can update the framework.

**Comment by PaymonK** [comment]
@Karvan Can you provide an example?

**Comment by Karvan** [comment]
` if (Quotation.PurchaseId != null) return ....;`

When `PurchaseId` is a nullable GUID, Gcup warns you to use HasValue while this extension is not available for the nullable GUID.

**Comment by mohsad06** [comment]
@PaymonK @Karvan Is this resolved or do I need to look into it?

**Comment by PaymonK** [comment]
@Karvan  please retest
