### ISSUE TITLE
Use of simple minus

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#90]
If you see:

`something = something * -1`

Then warn to say it should be written as:
`something = - something;`

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackages/ecf3a784f9db3934fa9a86cc739166a361441098](https://gitlab.com/Paymon/GCop/tree/ecf3a784f9db3934fa9a86cc739166a361441098)

**Comment by Foroughi** [comment]
Here are some details of the new rule : 

## General Details:

- ID : **544**
- Category : **Usage**
- Message : **It should be written as : {0}**
- Severity: **Warning**
- Package : **GCop.Common**

## Technical Details : 

The Rule will look for a equal expersion who: 

- Have a binary expersion on the right side
- The right side of that binary expersion  should be  -1
- The operator of that binary expersion should be *


## Test Result :

- [X]  x = x * -1
- [ ]  x = x * 1
- [ ]  x = x + -1
- [ ]  x = y * -1


In case of any changes needs to be done on this rule please let me know.
