### ISSUE TITLE
Rule help URLs

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/GCop#95]
The help URL of each rule should be to its corresponding page on GitHub:
https://github.com/Geeksltd/GCop/blob/master/Rules/GCop112.md

I expect that when pressing the link in Visual Studio, i'm taken to this page.

**Comment by Foroughi** [comment]
@repoter : Can I use this pattern as url for all rules ? : 

`https://github.com/Geeksltd/GCop/blob/master/Rules/GCop{{RuleKey}}.md `

**Comment by Karvan** [comment]
@Foroughi yes, please.

**Comment by Karvan** [comment]
@Foroughi Could you please update the pattern url to this one: 

`https://geeksltd.github.io/GCop/#/Rules/GCop{{RuleKey}}`

**Comment by Foroughi** [comment]
@reporter : Fixed on [NuGetPackages\3dc2bc16d443ab24e5f880cea10a540360ad746e](https://gitlab.com/Paymon/GCop/tree/3dc2bc16d443ab24e5f880cea10a540360ad746e)
